name: CI

on:
  push:
    branches:
      - "*"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install ``flake8``
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-import-order flake8-docstrings flake8-annotations
    - name: Lint with flake8
      run: |
        flake8
